# Generated by Django 2.2.6 on 2019-11-14 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkovChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Generator',
        ),
    ]
