# Generated by Django 2.2.6 on 2019-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0003_markovchain_dictogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='markovchain',
            name='slug',
            field=models.CharField(default='model-name', max_length=200),
            preserve_default=False,
        ),
    ]
