# Generated by Django 2.2.6 on 2019-11-21 19:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0005_auto_20191121_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markovchain',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='markovchain',
            name='dictogram',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
