# Generated by Django 2.2.6 on 2019-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0006_auto_20191121_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markovchain',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
