# Generated by Django 2.2.6 on 2019-12-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0007_auto_20191121_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markovchain',
            old_name='dictogram',
            new_name='start_tokens',
        ),
    ]
