# Generated by Django 2.2.6 on 2019-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0008_auto_20191203_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='markovchain',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
