# Generated by Django 2.2.6 on 2019-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0009_markovchain_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markovchain',
            old_name='start_tokens',
            new_name='dictogram',
        ),
    ]
