# Generated by Django 2.2.6 on 2019-12-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_generator', '0010_auto_20191203_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markovchain',
            old_name='dictogram',
            new_name='start_tokens',
        ),
    ]
